stages:
  - test
  - build
  - release

.go:
  image: public.ecr.aws/docker/library/golang:1.17
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache
  variables:
  before_script:
    - go mod download
  after_script:
    - mkdir -p .cache
    - cp -r $(go env GOPATH)/* .cache/

check:
  extends: .go
  stage: test
  script:
  - go install golang.org/x/tools/cmd/goimports@latest
  - go install gotest.tools/gotestsum@latest
  - go install github.com/boumenot/gocover-cobertura@latest
  - gofmt -d .
  - goimports -format-only -d .
  - go vet ./...
  - gotestsum --junitfile report.xml --format testname -- -coverprofile=cover.out -covermode count ./...
  - gocover-cobertura < cover.out > coverage.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml
    expire_in: 30 days