stages:
  - test
  - build
  - release

.go:
  image: public.ecr.aws/docker/library/golang:1.17
  cache:
    paths:
      - .cache
  variables:
    GOPATH: $CI_PROJECT_DIR/.cache
  before_script:
    - mkdir -p .cache
    - export GO_PKGS=$(go list ./... | grep -v .cache/)
    - go mod download

check:
  extends: .go
  stage: test
  script:
  - go install golang.org/x/tools/cmd/goimports@latest
  - go install gotest.tools/gotestsum@latest
  - go install github.com/boumenot/gocover-cobertura@latest
  - gofmt -d $GO_PKGS
  - goimports -format-only -d $GO_PKGS
  - go vet $GO_PKGS
  - gotestsum --junitfile report.xml --format testname -- -coverprofile=cover.out -covermode count $GO_PKGS
  - gocover-cobertura < cover.out > coverage.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml
    expire_in: 30 days