include:
  - project: tools/templates
    file: /ci/build-buildctl.yml

stages:
  - test
  - build
  - release


.go:
  image: public.ecr.aws/docker/library/golang:1.17
  tags: [new] # use new runners
  variables:
  before_script:
    - go mod download

check:
  extends: .go
  stage: test
  script:
  - go install golang.org/x/tools/cmd/goimports@latest
  - go install gotest.tools/gotestsum@latest
  - go install github.com/boumenot/gocover-cobertura@latest
  - gofmt -d .
  - goimports -format-only -d .
  - go vet ./...
  - gotestsum --junitfile report.xml --format testname -- -coverprofile=cover.out -covermode count ./...
  - gocover-cobertura < cover.out > coverage.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml
    expire_in: 30 days

.build-and-upload-binary:
  extends: .go
  stage: build
  needs: [check]
  script:
  - go build -race -o shipper ./cmd/shipper
  - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file shipper "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/shipper/$SHIPPER_VERSION/shipper"'

build-binary-unstable:
  extends: .build-and-upload-binary
  variables:
    SHIPPER_VERSION: unstable

build-container-unstable:
  extends: .build-with-buildctl
  stage: build
  needs: [check]
  tags: [new] # use new runners