project_name: shipper
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/shipper
archives:
  - replacements:
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  draft: true
  prerelease: auto
  header: |
    ## Shipper ({{ .Tag }})

    ### Changelog

    <copy the relevant CHANGELOG.md entries>

    ### Docker images
    - `docker pull ghcr.io/neosperience/shipper:{{ .Tag }}`
changelog:
  skip: true
